export const bookTitles = {
  en: [
    "Stranger in New York",
    "The Silent River",
    "100 Things To Do With Cars",
    "The Last Whisper",
    "Echoes of the Mind",
    "Dreams Beyond Time",
    "Voices in the Fog",
    "The Art of Disappearing",
    "The Edge of Tomorrow",
    "Secrets of the Willow Tree",
    "Whispers in the Dark",
    "Beyond the Horizon",
    "The Forgotten Garden",
    "Shadows of the Past",
    "Footprints on the Shore",
    "The Winter Letter",
    "Crimson Skies",
    "The Marble Heart",
    "Letters from Elsewhere",
    "The Clockmaker’s Dilemma",
    "The Hidden Manuscript",
    "The Storm Within",
    "A House of Broken Promises",
    "The Poet’s Ghost",
    "Between Two Suns",
    "A Map of Scars",
    "Where Wildflowers Bloom",
    "The Ink Beneath",
    "Serpents of the Valley",
    "The Lantern Keeper",
    "Twilight Promises",
    "Lost in Amber",
    "The Golden Paradox",
    "Fragments of the Sea",
    "The Orchard of Echoes",
    "A Symphony of Ash",
    "The Moonlit Staircase",
    "Threads of Tomorrow",
    "The Porcelain Veil",
    "Wings of Silence",
    "The Cursed Violin",
    "Tales from the Cellar",
    "The Hollow Library",
    "The Crimson Raven",
    "Violet Dawn",
    "Timekeeper’s Secret",
    "The Collector’s Truth",
    "The Broken Compass",
    "Crows in the Fog",
    "The Midnight Deal",
    "Harvest of Whispers",
    "The Lighthouse Pact",
    "Glassbound",
    "Whispers Beneath the Soil",
    "The Book of Forgotten Fires",
    "The Key of Thorns",
    "Memoirs of a Dying Tree",
    "Bitterwine",
    "The Chime of Dusk",
    "The Final Petal",
  ],
  fr: [
    "Marseille et la dame rose",
    "La librairie des livres interdits",
    "Il suffit parfois d'un été",
    "Le Bleu",
    "Bisous",
    "La grande arbre",
    "Les nuits de Provence",
    "Le secret des ombres",
    "Un été à Paris",
    "La route des souvenirs",
    "La forêt endormie",
    "Le silence des collines",
    "La mémoire du vent",
    "Le jardin oublié",
    "Les lanternes rouges",
    "L’écho du passé",
    "La voix de la mer",
    "Le pacte des étoiles",
    "L’ombre du lierre",
    "Les pages perdues",
    "La promesse d’automne",
    "L’empreinte du silence",
    "L’âme des pierres",
    "La porte de minuit",
    "La clef des songes",
    "L’atelier des secrets",
    "Le parfum de l’absence",
    "La lumière de l’hiver",
    "Les ailes de porcelaine",
    "Le manuscrit des murmures",
    "Le destin de la rose",
    "Le cercle des brumes",
    "Le cri des lucioles",
    "La chambre aux souvenirs",
    "La nuit de cristal",
    "L’orchestre invisible",
    "Le secret de la cascade",
    "Le miroir des saisons",
    "La dentelle des ombres",
    "L’arbre de verre",
    "Les ruines d’ivoire",
    "La chanson des feuilles",
    "La tour des murmures",
    "Les pas dans la neige",
    "Le serment de minuit",
    "Le crépuscule des cendres",
    "Le souffle du lys",
    "L’enfant du brouillard",
    "Les flammes silencieuses",
    "Le carnet du veilleur",
    "La voix des abeilles",
    "Les étoiles du grenier",
    "Le pacte des ombres",
    "Les lettres d’argile",
    "Le secret du verger",
    "Les chandelles de vent",
    "Le livre d’émeraude",
    "Le soupir des pierres",
    "La mémoire du grenadier",
    "Les contes du silence",
  ],
  de: [
    "Der Schatten im Wald",
    "Das verlorene Paradies",
    "Im Herzen der Zeit",
    "Die letzte Reise",
    "Der stille Beobachter",
    "Die Stimmen des Nebels",
    "Das Geheimnis der alten Villa",
    "Zwischen Licht und Dunkel",
    "Die Reise ins Morgen",
    "Der Ruf des Nordens",
    "Das Haus am Fluss",
    "Der Klang der Vergangenheit",
    "Der letzte Brief",
    "Die Spuren des Regens",
    "Im Takt der Schatten",
    "Der Spiegel des Winters",
    "Das Buch der Hoffnung",
    "Die Brücke zum Licht",
    "Der Duft der Erinnerung",
    "Das Flüstern der Berge",
    "Die Chroniken des Waldes",
    "Die Melodie der Stille",
    "Der Kreis der Echos",
    "Die Farben der Dämmerung",
    "Das Herz der Wildnis",
    "Die Zeiger des Schicksals",
    "Das Versprechen des Meeres",
    "Der Turm der Gedanken",
    "Die Glasinsel",
    "Die Rose aus Eisen",
    "Der Pfad der Seelen",
    "Das Licht hinter den Bäumen",
    "Die Gärten der Schatten",
    "Die Tore zur Stille",
    "Die Feder des Nordwinds",
    "Das Orakel der Blätter",
    "Die Laterne der Zeit",
    "Der Flug der Glühwürmchen",
    "Die Schrift im Sand",
    "Das Lied des Windes",
    "Der Kreis der Träume",
    "Die Farben des Abschieds",
    "Das geheime Archiv",
    "Die Wächterin der Stille",
    "Der Tanz der Federn",
    "Das Fest der Schatten",
    "Die Glocke des Morgens",
    "Die Maske des Herbstes",
    "Die Karte des Nebels",
    "Die Zeilen der Nacht",
    "Der Glanz des Verlorenen",
    "Die Stimme aus Stein",
    "Der Hauch des Vergessens",
    "Die Feder des Lichts",
    "Die Notizen des Reisenden",
    "Der Atem des Mooses",
    "Die Schritte im Tau",
    "Die Brücke der Worte",
    "Das Puzzle der Seele",
    "Die Laterne im Regen",
  ],
};

export const reviewTexts = {
  en: [
    "Absolutely loved it!",
    "A bit slow in the middle.",
    "Fantastic plot twists.",
    "Characters were deeply relatable.",
    "Would highly recommend!",
    "A thought-provoking read.",
    "Couldn't put it down.",
    "Very well written.",
    "A solid story with emotional depth.",
    "A poetic and powerful journey.",
    "Captivating from start to finish.",
    "Left me speechless.",
    "An emotional rollercoaster.",
    "Unforgettable characters.",
    "The writing style is exquisite.",
    "A masterpiece.",
    "Paced perfectly.",
    "Very realistic and immersive.",
    "Beautiful narrative voice.",
    "Charming and witty dialogues.",
    "Emotionally intense.",
    "Surprisingly moving.",
    "Hits all the right notes.",
    "Dark yet hopeful.",
    "A fresh perspective.",
    "Smart, sharp and suspenseful.",
    "Authentic and raw.",
    "A charming tale.",
    "Riveting storytelling.",
    "Well-developed plot arcs.",
    "A page-turner.",
    "So atmospheric!",
    "I got lost in this world.",
    "Truly unique.",
    "Exceptional story depth.",
    "A gem of a novel.",
    "Brilliant character development.",
    "Simply brilliant writing.",
    "Struck a chord with me.",
    "Emotionally powerful ending.",
    "Original and bold.",
    "Heartfelt and honest.",
    "Hits close to home.",
    "Leaves a lasting impression.",
    "Engaging from start to end.",
    "A delightful read.",
    "Narrative brilliance.",
    "A novel I will remember.",
    "Hauntingly beautiful.",
    "Really pulls you in.",
    "A story that lingers.",
    "Totally worth reading.",
    "Atmospheric and lyrical.",
    "Creative and surprising.",
    "Evocative and impactful.",
    "Powerful prose.",
    "Rich with emotion.",
    "Visually stunning storytelling.",
    "Satisfyingly complex characters.",
  ],
  fr: [
    "Une lecture captivante.",
    "Très bien écrit.",
    "Un peu lent au début.",
    "Les personnages sont attachants.",
    "Je recommande vivement.",
    "Un chef-d'œuvre littéraire.",
    "Une histoire riche en émotions.",
    "Superbe de bout en bout.",
    "Une intrigue fascinante.",
    "Des personnages inoubliables.",
    "Un récit touchant.",
    "Un style d'écriture exceptionnel.",
    "Un voyage poétique.",
    "Captivant du début à la fin.",
    "Un vrai coup de cœur.",
    "Émotionnellement intense.",
    "Des dialogues charmants et pleins d'esprit.",
    "Une histoire qui résonne.",
    "Un récit qui fait réfléchir.",
    "Une plume magnifique.",
    "Un roman inoubliable.",
    "Une aventure palpitante.",
    "Un souffle d'air frais.",
    "Une œuvre audacieuse.",
    "Un récit riche en détails.",
    "Une expérience immersive.",
    "Un délice à lire.",
    "Des rebondissements surprenants.",
    "Un final émouvant.",
    "Une belle narration.",
    "Une lecture mémorable.",
    "Un livre que je relirai.",
    "Un récit qui fait réfléchir.",
    "Une exploration fascinante.",
    "Des personnages bien développés.",
    "Un rythme parfait.",
    "Des thèmes universels.",
    "Une beauté poignante.",
    "Un style d'écriture fluide.",
    "Une histoire captivante.",
    "Une plume poétique.",
    "Un roman à ne pas manquer.",
    "Une lecture envoûtante.",
    "Un chef-d'œuvre moderne.",
    "Une intrigue bien ficelée.",
    "Une richesse d'émotions.",
    "Un univers unique.",
    "Une profondeur remarquable.",
    "Une lecture qui reste en mémoire.",
    "Un voyage à travers les émotions.",
    "Un récit enchanteur.",
  ],
  de: [
    "Ein fesselndes Buch.",
    "Gut geschrieben.",
    "Die Handlung war spannend.",
    "Sehr empfehlenswert.",
    "Charaktere waren überzeugend.",
    "Eine emotionale Reise.",
    "Ein literarisches Highlight.",
    "Ein Meisterwerk.",
    "Fesselnd von Anfang bis Ende.",
    "Ein unvergessliches Erlebnis.",
    "Der Schreibstil ist exquisit.",
    "Ein poetisches und kraftvolles Werk.",
    "Ein emotionales Auf und Ab.",
    "Einzigartige Charaktere.",
    "Eine brillante Erzählweise.",
    "Eine spannende Geschichte.",
    "Gut ausgearbeitete Handlungsstränge.",
    "Ein Pageturner.",
    "Atmosphärisch und lyrisch.",
    "Ein Buch, das zum Nachdenken anregt.",
    "Ein frischer Blickwinkel.",
    "Ein charmantes Märchen.",
    "Ein mitreißendes Abenteuer.",
    "Ein Buch, das man nicht aus der Hand legen kann.",
    "Ein eindrucksvolles Ende.",
    "Ein emotionaler Höhepunkt.",
    "Eine Geschichte, die im Gedächtnis bleibt.",
    "Ein tiefgründiger Roman.",
    "Eine fesselnde Erzählung.",
    "Ein Buch, das man gelesen haben muss.",
    "Ein wahrer Genuss.",
    "Ein Meisterwerk der Literatur.",
    "Ein außergewöhnliches Leseerlebnis.",
    "Eine packende Handlung.",
    "Ein Buch voller Emotionen.",
    "Ein einzigartiger Stil.",
    "Eine Geschichte, die berührt.",
    "Ein faszinierendes Universum.",
    "Ein Buch, das zum Träumen einlädt.",
    "Ein literarisches Juwel.",
    "Ein Meisterwerk der Erzählkunst.",
    "Ein Buch, das man nicht vergisst.",
    "Eine Reise durch die Gefühle.",
    "Ein zauberhaftes Werk.",
  ],
};
